### ISSUE TITLE
射爆了

### ISSUE THREAD

**Issue by icecliffs** [reisen1234/Data-structure#1]
好喜欢你的代码。

**Comment by reisen1234** [comment]
爬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月8日(周一) 晚上9:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [reisen1234/Data-structure] 射爆了 (Issue #1)




 
好喜欢你的代码。

**Comment by icecliffs** [comment]
> 爬
> 
> 
> 
> 
> 
> 
> 
> ---原始邮件---
> 
> 发件人: ***@***.***&gt;
> 
> 发送时间: 2024年1月8日(周一) 晚上9:32
> 
> 收件人: ***@***.***&gt;;
> 
> 抄送: ***@***.***&gt;;
> 
> 主题: [reisen1234/Data-structure] 射爆了 (Issue #1)
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 好喜欢你的代码。
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

![image](https://github.com/reisen1234/Data-structure/assets/48086093/aec17387-0b0b-4962-8155-61f51d67be81)
